---
all:
  children:

    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 93.77.191.250

    vector:
      hosts:
        vector-01:
           ansible_host: 111.88.247.242
           ansible_user: centos
           ansible_python_interpreter: /usr/local/bin/python3.8

    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 89.169.134.133

  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: ~/.ssh/id_rsa