---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - name: "clickhouse-common-static"
    url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-22.3.3.44.x86_64.rpm"
  - name: "clickhouse-client"
    url: "https://packages.clickhouse.com/rpm/stable/clickhouse-client-22.3.3.44.noarch.rpm"
  - name: "clickhouse-server"
    url: "https://packages.clickhouse.com/rpm/stable/clickhouse-server-22.3.3.44.noarch.rpm"